name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: dschep/install-pipenv-action@v1
    - name: Install pip dependencies
      run: pipenv install -d
    - name: Lint with flake8
      run: pipenv run flake8 .
